### ISSUE TITLE
Upgrading from non-versioned to versioned data. This backend will be unavailable for a brief period and will resume service shortly.

### ISSUE THREAD

**Issue by bulatster** [hashicorp/vault-plugin-secrets-kv#75]
Hi,
I get this error for kv v2 secrets engine with v2 syntax with `-mount` option, `vault kv put -mount=secret my-secret foo=a bar=b`.
Vault is deployed in kubernetes in HA mode with raft storage and UI enabled.

**Comment by ncabatoff** [comment]
Hi @bulatster,

This is a transient error that's seen sometimes right after mounting a KVv2 secrets engine.  We've fixed it in https://github.com/hashicorp/vault/pull/17406, which should be available in an upcoming 1.12 release.  Until then, I suggest retrying.
